FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat && \
    npm install -g pnpm && \
    addgroup -S nuxtgroup && \
    adduser -S nuxtuser -G nuxtgroup

COPY package.json pnpm-lock.yaml ./
# RUN pnpm fetch

COPY . .

RUN pnpm install 
    # chown -R nuxtuser:nuxtgroup /app

# USER nuxtuser

EXPOSE 3000
CMD ["pnpm", "run", "dev"]
