version: '3.8'
services:
  # nuxt-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: production
  #   volumes:
  #     - .:/app:delegated
  #     - /app/node_modules
  #   tmpfs:
  #     - /tmp
  #   restart: always

  nuxt-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
    volumes:
      - app_data:/app:delegated
    tmpfs:
      - /tmp
    restart: always

volumes:
  app_data:
